---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: petclinicapp
    labels:
        app: petclinicapp
        type: petclinicapp-dev
spec:
   selector:
      matchLabels:
         app: petclinicapp
         type: petclinicapp-dev
         
   template: 
       metadata: 
          name: petclinicapp-pod
          labels: 
              app: petclinicapp
              type: petclinicapp-dev

       spec: 
          containers:
            - image:  184.72.168.66:80/javaapp/petapp:latest
              imagePullPolicy: Always
              name:  petclinicapp
              ports:
                - containerPort: 8080
              readinessProbe: 
                  httpGet: 
                     path: /sample
                     port: 8080
          
   replicas: 3
---
apiVersion: v1
kind: Service
metadata: 
   name: petclinceapp-svc
   labels: 
       app: petclinicapp
       type: petclinceapp-svc

spec: 
    type: NodePort
    ports:
        - port: 80
          targetPort: 8080
          nodePort: 30036
          protocol: TCP
    selector: 
      app: petclinicapp
      type: petclinicapp-dev
   
